// lib/models/payment_transaction.dart

class PaymentTransaction {
  final String? id; // Transaction ID from backend
  final double amountDue;
  final String paymentMethod; // e.g., 'Cash', 'Card', 'UPI'
  final double? cashPaid; // Only relevant for cash payments
  final double? changeDue; // Only relevant for cash payments
  final String status; // 'pending', 'success', 'failed', 'processing'
  final DateTime? timestamp;

  PaymentTransaction({
    this.id,
    required this.amountDue,
    required this.paymentMethod,
    this.cashPaid,
    this.changeDue,
    this.status = 'pending',
    this.timestamp,
  });

  // Factory constructor to create a PaymentTransaction from a JSON map (for responses)
  factory PaymentTransaction.fromJson(Map<String, dynamic> json) {
    return PaymentTransaction(
      id: json['id'] as String?,
      amountDue: (json['amount_due'] as num?)?.toDouble() ?? 0.0,
      paymentMethod: json['payment_method'] as String? ?? 'N/A',
      cashPaid: (json['cash_paid'] as num?)?.toDouble(),
      changeDue: (json['change_due'] as num?)?.toDouble(),
      status: json['status'] as String? ?? 'pending',
      timestamp: json['timestamp'] != null ? DateTime.parse(json['timestamp']) : null,
    );
  }

  // Method to convert a PaymentTransaction to a JSON map (for sending to backend)
  Map<String, dynamic> toJson() {
    return {
      'amount_due': amountDue,
      'payment_method': paymentMethod,
      'cash_paid': cashPaid,
      'change_due': changeDue,
      // Status and timestamp might be generated by backend, or sent as initial 'pending'
      'status': status,
      'timestamp': timestamp?.toIso8601String(),
    };
  }

  // Helper method to create a copy with updated values
  PaymentTransaction copyWith({
    String? id,
    double? amountDue,
    String? paymentMethod,
    double? cashPaid,
    double? changeDue,
    String? status,
    DateTime? timestamp,
  }) {
    return PaymentTransaction(
      id: id ?? this.id,
      amountDue: amountDue ?? this.amountDue,
      paymentMethod: paymentMethod ?? this.paymentMethod,
      cashPaid: cashPaid ?? this.cashPaid,
      changeDue: changeDue ?? this.changeDue,
      status: status ?? this.status,
      timestamp: timestamp ?? this.timestamp,
    );
  }
}
